---
version: '3.4'
services:

  besu_node:
    image: hyperledger/besu:latest
    command: ["--network=dev",
              "--miner-enabled=true",
              "--miner-coinbase=0xfe3b557e8fb62b89f4916b721be55ceb828dbd73",
              "--rpc-http-cors-origins=*",
              "--host-allowlist=*",
              "--rpc-ws-enabled=true",
              "--rpc-http-enabled=true",
              "--rpc-http-api=ETH,NET,CLIQUE,DEBUG,MINER,NET,PERM,ADMIN,EEA,TXPOOL,PRIV,WEB3",
              "--engine-rpc-enabled=true",
              "--data-path=/var/lib/besu/data"]

    volumes:
      - ./besu:/var/lib/besu/data
    ports:
      # Map the p2p port(30303), RPC HTTP port(8545), and engine port (8551)
      - "18545:8545"
      - "18551:8551"
      - "30303:30303/tcp"
      - "30303:30303/udp"
